In [1]:
from pandas import read_csv
import seaborn as sns 
import numpy as np 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_regression
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['smoker']=lb.fit_transform(df['smoker'])
df['sex']=lb.fit_transform(df['sex'])
df['time']=lb.fit_transform(df['time'])
df['day']=lb.fit_transform(df['day'])

In [3]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [4]:
x

tip  sex  smoker  day  time  size
0    1.01    0       0    2     0     2
1    1.66    1       0    2     0     3
2    3.50    1       0    2     0     3
3    3.31    1       0    2     0     2
4    3.61    0       0    2     0     4
..    ...  ...     ...  ...   ...   ...
239  5.92    1       0    1     0     3
240  2.00    0       1    1     0     2
241  2.00    1       1    1     0     2
242  1.75    1       0    1     0     2
243  3.00    0       0    3     0     2

[244 rows x 6 columns]

In [5]:
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [6]:
x=df.drop('tip',axis=1)
y=df.tip

In [7]:
x

total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     0     2
1         10.34    1       0    2     0     3
2         21.01    1       0    2     0     3
3         23.68    1       0    2     0     2
4         24.59    0       0    2     0     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     0     3
240       27.18    0       1    1     0     2
241       22.67    1       1    1     0     2
242       17.82    1       0    1     0     2
243       18.78    0       0    3     0     2

[244 rows x 6 columns]

In [8]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [9]:
test = SelectKBest(score_func=f_regression,k=3).fit(x,y)
test

SelectKBest(k=3, score_func=<function f_regression at 0x00000180905B1440>)

In [10]:
test.pvalues_

array([6.69247065e-34, 1.66456235e-01, 9.26593152e-01, 8.57576987e-01,
       5.78015348e-02, 4.30054333e-16])

In [11]:
np.round(test.pvalues_,3)

array([0.   , 0.166, 0.927, 0.858, 0.058, 0.   ])

In [13]:
df.columns[test.get_support(indices=True)]

Index(['total_bill', 'day', 'time'], dtype='object')

In [14]:
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [15]:
x=df.iloc[:,0:4]

In [16]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [17]:
y=df['species']

In [18]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [19]:
sel=SelectKBest(score_func=chi2,k=2).fit(x,y)
sel

SelectKBest(k=2, score_func=<function chi2 at 0x00000180905B11C0>)

In [20]:
sel.pvalues_

array([4.47651499e-03, 1.56395980e-01, 5.53397228e-26, 2.75824965e-15])

In [21]:
sel.scores_

array([ 10.81782088,   3.7107283 , 116.31261309,  67.0483602 ])

In [22]:
sel.get_support(indices=True)

array([2, 3], dtype=int64)

In [23]:
df.columns[np.where(sel.get_support(indices=True))]

Index(['sepal_length', 'sepal_width'], dtype='object')